### ISSUE TITLE
What should the Chocolatey package title/id be?

### ISSUE THREAD

**Issue by AnthonyMastrean** [sikuli/sikuli#11]
[Here](https://github.com/sikuli/sikuli/issues/8#issuecomment-3763674) you said

> you should change the headline to "Sikuli X 1.0.3" and add a short comment, that the user knows, he gets what officially is called Sikuli X 1.0rc3 (because this is how we talk at the launchpad Q&A and bugs about it)

Is the project officially called "Sikuli X"? If so, I can change the Title of the package (that shows up in bold on the web gallery). And the package id "sikulix" is still available if you'd like to use that for new packages.

**Comment by RaiMan** [comment]
Yes the project as such is called "Project Sikuli" (the story behind is automation and testing using visual objects in general), but the current version under development is Sikuli X.

And this is what people get with your Chokolatey package.

Before switching to github, the versions where hosted on launchpad. There you can still download previous versions.

So I think "Sikuli X 1.0.3" would be the best choice for the package head line.

**Comment by AnthonyMastrean** [comment]
On the gallery, the title is displayed with the version, like 

> [title] [version]

So, I'll set the title to "Sikuli X" and whatever version is current will be displayed

> Sikuli X 1.0.0-rc3

**Comment by RaiMan** [comment]
seems to be fixed
