### ISSUE TITLE
How should we specify the Chocolatey package version?

### ISSUE THREAD

**Issue by AnthonyMastrean** [sikuli/sikuli#12]
There's a small problem, [NuGet](http://docs.nuget.org/docs/Reference/Versioning), the underlying technology to Chocolatey, [does not support](http://nuget.codeplex.com/discussions/283794#post715745) the latest semver spec. Which would have us version the package like this 

```
1.0.0-rc.3+build.905
```

However, NuGet will only support the old spec, with an arbitrary string appended

```
1.0.0-rc3build905
```

If you only publicly release incremented RC versions, then we can make it a little sexier

```
1.0.0-rc3
```

**Comment by AnthonyMastrean** [comment]
I'm [unable](https://twitter.com/#!/AnthonyMastrean/status/164900138421202944) to get _any_ of the prerelease version specs to work! These all fail
- 1.0.0-rc.3 (the nuget team admits this spec is too new)
- 1.0.0-rc3 (one doc suggests this is the way to do it)
- 1.0.0rc3 (and another doc suggests, this one)

**Comment by RaiMan** [comment]
Ok, let's stay with your first choice 1.0.3 with a little comment on how to translate it to Sikuli's current naming.

BTW: I am not one of the developers. I am only something like a Sikuli power user, who has a hobby: "helping people with Sikuli challenges".

I will suggest to the developers to switch to the above version numbering with the next release.

**Comment by AnthonyMastrean** [comment]
Oh wait, my bad, I had an old version of the nuget.exe. I got the latest (nuget 1.6) and it works with `1.0.0-<arbitrarystring>`. So, I can do 

```
1.0.0-rc3
```

or

```
1.0.0-rc3build905
```

What do you think? If we only release new RCs, I'd go with the first option.

**Comment by RaiMan** [comment]
Lets take the second version, so we would be compatible with the hudson number, if the master here on github gets updated.

**Comment by AnthonyMastrean** [comment]
I got NuGet to create the package from the spec, but now I can't get Chocolatey to install it. I'll keep working on that :(

**Comment by RaiMan** [comment]
seems to be fixed

**Comment by AnthonyMastrean** [comment]
Yeah, sorry, I've gotten busy at work & home. I'll be able to pick back up on this in the next few weeks. I'm opening a new issue to track the conversation/work on Chocolatey supporting the newest version spec.
