### ISSUE TITLE
What environment variables should be added when installing the portable package?

### ISSUE THREAD

**Issue by AnthonyMastrean** [sikuli/sikuli#13]
[Here](https://github.com/sikuli/sikuli/issues/8#issuecomment-3763674) you say 

> When using the installer version (.exe), the system path entries (path-to-Sikuli\libs and path-to-java\jre6\bin) and the environment variable %SIKULI_HOME% pointing to the folder where Sikuli is installed are setup by the installer.
> When using the zip download, you have to do it yourself.
> %SIKULI_HOME% is needed for some special cases, when running scripts from command line.

Am I correct thinking that we have to add 2 paths to the environment PATH?
1. `<path-to-sikuli>\libs`
2. `<path-to-java>\jre6\bin`

And add one custom environment variable
1. `SIKULI_HOME = <path-to-sikuli>`

**Comment by AnthonyMastrean** [comment]
I'd probably rather update the java runtime package to put the JRE in the PATH. The x86 JRE is always installed here?

```
%programfiles(x86)%\Java\jre6\bin
```

**Comment by RaiMan** [comment]
absolutely right.
