### ISSUE TITLE
Which link should the Chocolatey package set for each environment (x86/x64)?

### ISSUE THREAD

**Issue by AnthonyMastrean** [sikuli/sikuli#14]
[Here](https://github.com/sikuli/sikuli/issues/8#issuecomment-3763674) you say 

> The cited text from the home page is a bit misunderstandable: What it wants to say is: on 64Bit Windows do not use the .exe (it simply does not work) but one of the .bat's instead.

So on an x64 environment, we should link to the `sikuli-ide-w.bat` file. And on an x86 environment, should I link to the same (to keep the package simple) or is there a reason to link right to the `sikuli-ide.exe`?

**Comment by RaiMan** [comment]
When using the Sikuli installer, the desktop shortcut is set to Sikuli-IDE.exe. On some systems the .exe does not work, so people are encouraged to use one of the .bat's to start Sikuli-IDE.

I think it is ok, to link to Sikuli-IDE-w.bat in both environments.

**Comment by AnthonyMastrean** [comment]
This is done in my [branch](https://github.com/AnthonyMastrean/sikuli/blob/chocolateypackage/chocolateyInstall.ps1#L16).

**Comment by RaiMan** [comment]
Fine. Thanks.
