### ISSUE TITLE
The Chocolatey package should specify the Java Runtime dependency

### ISSUE THREAD

**Issue by AnthonyMastrean** [sikuli/sikuli#15]
The Chocolatey package currently specifies a dependency on the [Java Runtime](http://chocolatey.org/packages/javaruntime) (another package I created/uploaded to support this package). If you use the Chocolatey Install command, it will get installed too

```
cmd> chocolatey install sikuli
```

or 

```
cmd> cinst sikuli
```

I can fix up the java runtime version spec to limit it to any version between 6.0 (inclusive) and 7.0 (exclusive).

```
<dependency id="javaruntime" version="[6.0,7.0)" />
```

**Comment by RaiMan** [comment]
With the current version X-1.0rc3, only JRE 6 should be installed automatically if not present, since there are problems with JRE 7.

**Comment by AnthonyMastrean** [comment]
Yes. The notation `version=[6.0,7.0)` means that the version will be `>= 6.0` but `< 7.0`. So 7 is _excluded_.
