### ISSUE TITLE
Track Chocolatey support for the version spec we want to use.

### ISSUE THREAD

**Issue by AnthonyMastrean** [sikuli/sikuli#16]
Chocolatey has been updated internally to the latest NuGet version, which supports the latest version specification. If this works, the "newest" Sikuli X package version (`1.0.0-rc3`) will actually be lower than the one I originally uploaded (`1.0.3`). I will contact the Chocolatey gallery admin and explain the circumstances.

**Comment by vgod** [comment]
Is it possible to withdraw the 1.0.3 package and use 1.0.0-rc3 instead?

**Comment by AnthonyMastrean** [comment]
Yes, I am going to contact the Chocolatey author/admin and talk about this situation.
