### ISSUE TITLE
Sample structure for sikuli using maven

### ISSUE THREAD

**Issue by acdurai** [sikuli/sikuli#18]
Hi all

I am new to sikuli.

this tool very beautiful to test the gui
i don't know the maven structure for sikuli
if any one knows show the sample structure and pom

Thanks in advance 
Chelladurai.A

**Comment by RaiMan** [comment]
To build it?

or to use it with Java as a dependency?

**Comment by vnickolov** [comment]
Can sikuli-script be used as Java dependency without installing Sikuli?

**Comment by RaiMan** [comment]
@vnickolov 
switch to new version 1.1.0/1.1.1
http:/sikulix.com

**Comment by Hari6633** [comment]
@vnickolov
it is better to switch to new version 1.1.0/1.1.1
http:/sikulix.com

**Comment by RaiMan** [comment]
No longer supported
