### ISSUE TITLE
run(command) spawn new console

### ISSUE THREAD

**Issue by wernight** [sikuli/sikuli#21]
In GUI mode the `run(command)` should show the console window.

In CLI mode the `run(command)` could optionally show the console window.

Either way, it should check the exit code and either return it or fail.

Without such improvement, it's just like `submodule.call()`

**Comment by RaiMan** [comment]
Thanks for the comment.

actually the run() command is implemented using java.lang.Runtime.getRuntime().exec(command string) and it returns the command output as a list of lines.
This is comparable to an implementation on the Jython level using os.popen() (or subprocess.popen() better).

In both cases these commands are run in a separate process and do not have a console window at all (just sysin, sysout and syserr).

Nevertheless: I have it on my list to improve it. And to optionally show the command output in a window seems to be a good idea.

**Comment by wernight** [comment]
It would be useful to show in Sikuli documentation how to retrieve the output.

Please also give a way to retrieve the exit code and/or automatically fails unless it's zero.

Usage example:
- compile the solution (shouldn't fail else you might end up testing an older version)
- restore a database
- ...

**Comment by RaiMan** [comment]
No longer supported
