### ISSUE TITLE
Incorrect form of "its" and "it's" used in documentation

### ISSUE THREAD

**Issue by alistair-broomhead** [sikuli/sikuli#27]
I know this is really pedantic but:

I noticed at 2 points in the Region class documentation that "it's" has been used to refer to something belonging to "it" where "its" should be used - "it's" is a contraction of "it is" - I would guess this is not the only part of the documentation where this mistake has been made; I would suggest getting someone to proofread it all before the next major release.

**Comment by RaiMan** [comment]
Thanks, I have put it on the list.
