### ISSUE TITLE
Part of a dialog window gets black 

### ISSUE THREAD

**Issue by alexlucky** [sikuli/sikuli#28]
Hi,Team,

I have been using Sikuli for my tests and i find it very useful. But i ran into a issue today.
I am running my test on a vnc session, and the test script exits due the following reason:
During my testing process, a button click action failed due to part of the dialog window gets black, which covers the "connect" button.
However, if I move the dialog this won't happen anymore, so I can still run my script just dragging and dropping my dialog before performing my actions on this dialog.

Have you ever met this kind of issue before? Can you give me some advice?Thank you for your time.

**Comment by RaiMan** [comment]
No longer supported
