### ISSUE TITLE
"wait(target, timeout)" doesn't wait until the timeout supplied

### ISSUE THREAD

**Issue by marineni** [sikuli/sikuli#29]
The application I am testing has steps where sometimes the next step response time can be quick but sometimes it can take longer.

"wait(target, timeout)" is really useful as I can request to wait until target appears or until the maximum timeout supplied.

But I have observed that this function does not use the timeout supplied, instead waits until the auto wait timeout. I have actually verified this: 

before setting auto wait timeout:- 
        screen.wait(DATAMART_CREDENTIALS_LABEL, DB_CONNECTION_WAIT_TIME);
    FindFailed error occurs. As it waits for the default auto wait not the timeout supplied.

after setting auto wait timeout:-
        screen.setAutoWaitTimeout(DB_CONNECTION_WAIT_TIME);
        screen.wait(DATAMART_CREDENTIALS_LABEL, DB_CONNECTION_WAIT_TIME);
    Waits until the image is found as the auto wait timeout is longer than the default and hence runs successfully. 

Can I request the team to kindly fix this issue as It would really be helpful if this function actually works.

**Comment by RaiMan** [comment]
I will check this and provide a fix with the new version.

**Comment by marineni** [comment]
Thank you!

**Comment by RaiMan** [comment]
seems to be fixed with the build 2013-09-12

**Comment by Ramanth** [comment]
does this command just wait for the element to appear or clicks on the element after it appears?
im looking for just waiting till the element appear, is there a method for that?

**Comment by RaiMan** [comment]
No longer supported
