### ISSUE TITLE
Can Sikuli work with iPhone real device ?

### ISSUE THREAD

**Issue by giteshgarg** [sikuli/sikuli#30]
I am able run sikuli scripts on iPhone simulator but not able to execute on iPhone real device...Is it possible with iPhone real device ?

Thanks.

**Comment by marineni** [comment]
Hi, I have not worked with Sikuli on iPhone so, I do not know if it works.

Cheers,
Swetha.

**Comment by RaiMan** [comment]
simply: no.

May be one day, who knows?
