### ISSUE TITLE
bug with drop action

### ISSUE THREAD

**Issue by walty8** [sikuli/sikuli#32]
in file: 
./src/main/java/org/sikuli/slides/api/actions/DropAction.java

line 21, it is:
mouse.drag(loc);

but it should be:
mouse.drop(loc);

thanks.

**Comment by RaiMan** [comment]
Wrong place here ;-)
look: https://code.google.com/p/sikuli-api/

**Comment by walty8** [comment]
I am sorry for the confusion, so I should put the report in the google code -> sikuli api, instead of github -> sikuli api?

thanks

**Comment by RaiMan** [comment]
no problem, yes.
