### ISSUE TITLE
doFind error in GUI generated Regions

### ISSUE THREAD

**Issue by fprivitera** [sikuli/sikuli#33]
I succeeded on installing sikulix on windows 7, I run a small script with :

while exists(REGION):

where REGION was a GUI generated region, the program started but had a fatal error soon: 

[error (06/06/14 9.51.45)] Region: doFind: invalid parameter: R[315,731 42x21]@S(0)[0,0 1366x768] E:Y, T:3,0
[error (06/06/14 9.51.45)] Terminating SikuliX after a fatal error(1)! Sorry, but it makes no sense to continue!

**Comment by RaiMan** [comment]
this version is no longer maintained here.

Use Launchpad for your questions and bug reports.

Furthermore, this does not seem to be this version (1.0rc3), but version 1.0.1

exists() needs an image as prameter and not a region.
