### ISSUE TITLE
Windows: User Path variable

### ISSUE THREAD

**Issue by meeech** [sikuli/sikuli#34]
I think when installed on Windows 7 overwrites the User PATH variable rather than append to it

**Comment by RaiMan** [comment]
talking about 1.1.0 or 1.0.1?

**Comment by meeech** [comment]
1.0.1

**Comment by RaiMan** [comment]
yes, known problem - fixed in 1.1.0

to avoid this in 1.0.1, take care that an entry for <path-to-siikulix>\libs is in the system path at runtime.
