### ISSUE TITLE
Add support for non-ascii path

### ISSUE THREAD

**Issue by niconiconi** [sikuli/sikuli#36]
It crash when the path has non-ascii characters.

![image](https://cloud.githubusercontent.com/assets/8384567/11115887/83b3bfe8-8969-11e5-85ab-f397a7b0f567.png)
![image](https://cloud.githubusercontent.com/assets/8384567/11115939/d1daca18-8969-11e5-9cec-e027bb46061d.png)

**Comment by niconiconi** [comment]
the version is 1.1.0

**Comment by RaiMan** [comment]
wrong place here.
moved to:
https://github.com/RaiMan/SikuliX-2014/issues/175
