### ISSUE TITLE
Using SikuliX

### ISSUE THREAD

**Issue by NithyaRevankar** [sikuli/sikuli#46]
We are planning to use in a large scale project. do you recommend using SikuliX or you have some thing else in your bucket which can help us.

**Comment by JoelStienlet** [comment]
Hello! If your project is large (but it would help if "large" were defined in a more quantitative way), the time spent making preliminary tests to see if this library will suit your needs will not weight against the development time of the whole project I think. Just my 2 cent ;)

**Comment by RaiMan** [comment]
@NithyaRevankar 
Please be more precise:
- do you plan a project, where SikuliX features are part of your project features?
- or do you plan to use SikuliX as a test tool for the features of your project?

**Comment by NithyaRevankar** [comment]
@RaiMan 

Thank you so much for your reply.

We are planning to use SikuliX as a automation test tool for testing our desktop application which is similar to Auto cad (basically a reverse engineering application).

**Comment by RaiMan** [comment]
Use latest version (1.1.3)
http://sikulix.com

Start with the SikuliX IDE and make short and representative tests, to prove the useability of the SikuliX visual approach in your project testing.

Then decide about how to implement the tests in you test environment (python scripting/unittest, RobotFramework, Java programming with a unittesting framework, ...).
