### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by pllim** [sikuli/sikuli#48]
Hi. I have never used Sikuli before but am interested to know more. On your http://sikulix-2014.readthedocs.io/en/latest/index.html page, it says, "Python (language level 2.7) supported by the Jython interpreter." I am wondering if Sikuli is compatible with Python 3, specifically 3.5+. Thank you.

**Comment by RaiMan** [comment]
as it is said:
Python (language level 2.7) supported by the Jython interpreter

The useable language level depends on what Jython supports and this currently is max. 2.7

**Comment by pllim** [comment]
Ah, gotcha. I also found https://stackoverflow.com/questions/2351008/when-will-jython-support-python-3 . Thank you for the clarification.
