### ISSUE TITLE
sikuli script does not execute on jenkins

### ISSUE THREAD

**Issue by karnikmg** [sikuli/sikuli#49]
Platform- MAC
OS- MAC OS high Sierra

Problem-
I am able to run sikuli script locally on my machine as we jenkins local machine, but if i trigger build to run automation on jenkins, then it got fail. I am performing file upload on mac.

**Comment by RaiMan** [comment]
Sikuli always needs a real screen to work.

A Jenkins environment usually is headless (no screen) - hence Sikuli does not work.

Search in the net for solutions, how to run some "fake screen" based on X11 solutions.
