### ISSUE TITLE
"Unexpected end of ZLIB input stream" Exception occur when install

### ISSUE THREAD

**Issue by etiaxie** [sikuli/sikuli#50]
the setup log like this:
[... some stuff ...]
[debug (18-6-28 16:22:27)] RunSetup: Downloads for selected options:
sikulixlibswin-1.1.1.jar sikulixsetupIDE-1.1.2-20180308.083933-100-forsetup.jar sikulixsetupAPI-1.1.2-20180308.083909-100-forsetup.jar jython-standalone-2.7.1.jar 
[debug (18-6-28 16:22:27)] RunSetup: adding needed stuff to sikulix.jar
[debug (18-6-28 16:22:27)] FileManager: buildJar: sikulixtemp.jar
[debug (18-6-28 16:22:27)] FileManager: buildJar: adding: sikulix.jar
[debug (18-6-28 16:22:33)] FileManager: buildJar: adding: sikulixjython.jar
[error (18-6-28 16:22:40)] FileManager: buildJar: java.io.EOFException: Unexpected end of ZLIB input stream
[debug (18-6-28 16:22:40)] RunSetup: renaming sikulixtemp.jar to target jar: sikulix.jar
[debug (18-6-28 16:22:40)] RunSetup: rename did not work --- trying copy
[debug (18-6-28 16:22:40)] FileManager: deleteFileOrFolder:
C:\Users\xietian\Desktop\skuli\sikulixtemp.jar
[error (18-6-28 16:22:40)] RunSetup: did not work
[error (18-6-28 16:22:40)] RunSetup: 
[error (18-6-28 16:22:40)] RunSetup: ... terminated abnormally :-(
[debug (18-6-28 16:22:40)] RunSetup: 
popError: --------------------
Something serious happened! Sikuli not useable!
Check the error log at C:\Users\xietian\Desktop\skuli\SikuliX-1.1.2-SetupLog.txt
[debug (18-6-28 16:22:44)] RunTimeSETUP: final cleanup
[debug (18-6-28 16:22:44)] FileManager: deleteFileOrFolder:
C:\Users\xietian\AppData\Local\Temp\SikuliX-1.1.2-SetupLog.000
[debug (18-6-28 16:22:44)] FileManager: deleteFileOrFolder:
C:\Users\xietian\AppData\Local\Temp\Sikulix_601888068

**Comment by RaiMan** [comment]
Questions like this should be asked on Launchpad!

Delete all stuff that was downloaded and or created and start over again.
