### ISSUE TITLE
By using the Sikuli Screen class, the maven surefire plugin exception is thrown when running the test from TeamCity

### ISSUE THREAD

**Issue by arsen-papoyan** [sikuli/sikuli#55]
When I run a test with Sikuli Screen class on a local machine or from a local machine into a remote server, the test runs without error, but when I run the same test from CI (TeamCity), I get this error:

> Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project myProject: There are test failures.
> [ERROR] 
> [ERROR] Please refer to /root/work/myProject/target/surefire-reports for the individual test results.
> [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
> [ERROR] There was an error in the forked process
> [ERROR] 
> [ERROR] Cannot instantiate class com.bme.test.SikuliExampleTest
> [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
> [ERROR] 
> [ERROR] Cannot instantiate class com.bme.test.SikuliExampleTest
> [ERROR]     at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:733)
...

Other tests run from TeamCity also work without errors.
POM:

```
<plugin>
     <groupId>org.apache.maven.plugins</groupId>
     <artifactId>maven-surefire-plugin</artifactId>
     <version>3.0.0-M5</version>
 </plugin>

   <dependency>
        <groupId>com.sikulix</groupId>
        <artifactId>sikulixapi</artifactId>
        <version>2.0.4</version>
    </dependency>
```

**Comment by RaiMan** [comment]
It does not make it better, when you simply post the same incomplete information somewhere else.

This is the wrong place (what is mentioned in the READ.ME).

Please stay with your question on Launchpad and provide SikuliX specific information.
