### ISSUE TITLE
Have a local build script for win32

### ISSUE THREAD

**Issue by AnthonyMastrean** [sikuli/sikuli#7]
I would like to build Sikuli for win32 from the command line using a script that's included in the root of the repository. I see a `build-win32.txt` file and I started turning it into a batch script. But, I realized that your [Hudson server](http://sikuli.org/hudson/job/Sikuli-Script-Windows/159/console) must have a script or something on it for this already. Can you pull it out of there and check it in?

**Comment by RaiMan** [comment]
I guess, the build script running on the hudson server does not contain the preliminaries that have to be fulfilled, before starting to build Sikuli itself (OpenCV, tesseract, swig and more). 

The system, that runs the build is already setup for that.

And I guess, the continuos build run on hudson is simply the nmake command, that calls the main make file.

**Comment by AnthonyMastrean** [comment]
The prerequisites are mentioned in build-win32.txt. Assume the system is setup properly. The CMake commands will complain if any of the `find_path` calls fail. Maybe you can provide some information about how to configure each prerequisite. For example, where do I put the tesseract source to satisfy the CMake script? Does it have to be in my PATH or at C:\ (like it is in Hudson)?

**Comment by RaiMan** [comment]
work finished with https://github.com/sikuli/sikuli/issues/10
